### DISCUSSION TITLE
PathPrefix Issues

### DISCUSSION THREAD

**Discussion by mo-jo-lo** [gomods/athens#1648] [General] [answered]
I am trying to run an athens instance behind a reverse proxy on port 80 via PathPrefix. I have created a minimal
`docker-compose.yml` I want to share

version: '3.3'

```yml
services:
  traefik:
    container_name: traefik
    image: traefik:v2.2
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  athens:
    container_name: athens
    image: gomods/athens:v0.10.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.athens.entrypoints=web"
      - "traefik.http.routers.athens.rule=Host(`localhost`) &&
      PathPrefix(`/athens`)"
    environment:
      - ATHENS_PATH_PREFIX=athens
    ports:
      - 3001:3000
```

Unfortunately I always get a `404 error`.
If I remove the environment variable and directly navigate to `localhost:3001`, it works.
Thank you very much!

**Comment by arschles** [comment]
whoa @ftrier I never saw this in here. we don't check GitHub discussions, but clearly we should. are you getting a 404 when you `curl` the Athens server?

**Reply by mo-jo-lo** [reply]
Hello arschles,
I am sorry, currently I don't have the means to reproduce the problem. If the problem still exists, I could setup my system to help investigate.

**Comment by chennin** [comment, marked as answer]
I also had this problem. It seems a beginning slash is required.

**REPRODUCE FAILURE**:

```
  go-proxy:
    image: gomods/athens:latest
    environment:
      ATHENS_PATH_PREFIX: "go"
```

```bash
~ $ curl http://go-proxy:3000/go/readyz
404 page not found
```

**SUCCESS**:

```
  go-proxy:
    image: gomods/athens:latest
    environment:
      ATHENS_PATH_PREFIX: "/go"
```

```bash
~ $ curl -v http://go-proxy:3000/go/readyz
...
< HTTP/1.1 200 OK
...
```
