### ISSUE TITLE
Fail to access private bitbucket repository

### ISSUE THREAD

**Issue by chengjingtao** [gomods/athens#1265]
**Describe the bug**
Hi, I have met some questions about `access bitbucket private repository`.
I deployed `athens` on kubernetes cluster and fllowed  doc https://docs.gomods.io/install/install-on-kubernetes/.
I am sure  somethings works well
1.  I could clone my private repository in athens-proxy pod. ( correct ssh-key has been set in pod )
2. Already change  `git@bitbucket.org:` instead of `https://bitbucket.org/`
3. Already set GOPROXY
But when I build my source code.  It shows erros :
 
```
go: finding bitbucket.org/xxx/xxx v0.0.0-20190602054948-b18ac19094f0
Fetching https://athens.mysite.cn/bitbucket.org/xxx/xxx/@v/v0.0.0-20190602054948-b18ac19094f0.info
go: bitbucket.org/xxx/xxx@v0.0.0-20190602054948-b18ac19094f0: unexpected status (https://athens.mysite.cn/bitbucket.org/xxx/xxx/@v/v0.0.0-20190602054948-b18ac19094f0.info): 404 Not Found
go: error loading module requirements
```
The problem is:  `go mod` cannot get the module of  private bitbucket repository.

When I remove the setting of `upstreamProxy` and deploy it again.  It works well.

**Informations to reproducce**

```bash
helm install gomods/athens-proxy -n athens --namespace athens -f athens.values.yaml
```
```yaml
#  athens.values.yaml
sshGitServers: 
  ## Private git servers over ssh
  ## to enable uncomment lines with single hash below
  ## hostname of the git server
  - host: bitbucket.org
    ## ssh username
    user: xxx
    ## ssh private key for the user
    privateKey: |
      -----BEGIN RSA PRIVATE KEY-----
      xxxxxxx
      -----END RSA PRIVATE KEY-----
    port: 22
storage:
  type: disk
  disk:
    storageRoot: "/var/lib/athens"
    persistence:
      ## Note if you use disk.persistence.enabled, replicaCount should be set to 1 unless your access mode is ReadWriteMany
      enabled: true
      accessMode: ReadWriteMany
      size: 20Gi
      storageClass: managed-nfs-storage
ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx/client_max_body_size: "0"
  hosts: 
    - athens.mysite.cn
  tls:
    - secretName: athens.mysite.cn
      hosts:
        - athens.mysite.cn
upstreamProxy:
  enabled: true
  url: "https://gocenter.io"
```

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04.1 LTS
 -  Helm Version: v2.13.1 
 - Proxy version : chart 0.2.7
