### ISSUE TITLE
Cannot use Aliyun  OSS storage

### ISSUE THREAD

**Issue by wangycc** [gomods/athens#1308]
**Describe the bug**
When I use aliyun oss, the pull package fails

**Error Message**
<pre>
```console
time="2019-07-18T06:19:38Z" level=error msg="Aws MultiChunkedEncoding is not supported." http-method=GET http-path=/github.com/athens-artifacts/samplelib/@v/v1.0.0.info http-url=/github.com/athens-artifacts/samplelib/@v/v1.0.0.info kind="Internal Server Error" module=github.com/athens-artifacts/samplelib operation=download.InfoHandler ops="[download.InfoHandler pool.Info protocol.Info protocol.processDownload stash.Pool stasher.Stash storage.minio.Save]" version=v1.0.0
```
</pre>

**Environment (please complete the following information):**
 - OS: The official docker
 - Go version : go version go1.12.4 darwin/amd64
 - Proxy version : gomods/athens:v0.5.0
 - Storage (fs/mongodb/s3 etc.) : aliyun oss

**configuration**
```toml
StorageType = "minio"
[Storage]
    [Storage.Minio]
        #Endpoint = "oss-cn-hangzhou-internal.aliyuncs.com"
        Endpoint = "oss-cn-hangzhou.aliyuncs.com"
        Key = "xxxx"
        Secret = "xxxx"
        EnableSSL = false
        Bucket = "athens"
        Region = ""
```
