### ISSUE TITLE
Deployment to kubernets

### ISSUE THREAD

**Issue by sah4ez** [gomods/athens#1367]
In [this condition](https://github.com/gomods/athens/blob/master/charts/athens-proxy/templates/deployment.yaml#L146) missed the values for `sshGitServers` ([there](https://github.com/gomods/athens/blob/master/charts/athens-proxy/templates/deployment.yaml#L163))

```
{{- if or (eq .Values.storage.type "disk") .Values.upstreamProxy.enabled .Values.netrc.enabled }}
   volumeMounts:
{{- end }}
```
when I tried install to helm, I got an error:
```
$ helm install --namespace kube-public -f athens.yaml --set storage.mongo.url=mongodb://mongo.default.svc.cluster.local:27017 -n athens gomods/athens-proxy
Error: release athens failed: Deployment.apps "athens-athens-proxy" is invalid: [spec.template.spec.containers[0].ports[1].name: Invalid value: "ssh-git-servers-config": must be no more than 15 characters, spec.template.spec.containers[0].ports[1].containerPort: Required value, spec.template.spec.containers[0].ports[2].name: Invalid value: "ssh-git-servers-config": must be no more than 15 characters, spec.template.spec.containers[0].ports[2].containerPort: Required value, spec.template.spec.containers[0].ports[3].containerPort: Required value]
```
I disabled `upstreamProxy`, `netrc` and used `type: mongo` in storage.

**Comment by sah4ez** [comment]
helm template contains:
```
 env:
        - name: ATHENS_GOGET_WORKERS
          value: "3"
        - name: ATHENS_STORAGE_TYPE
          value: "mongo"
        - name: ATHENS_MONGO_STORAGE_URL
          value: "mongodb://mongo.default.svc.cluster.local:27017"
        ports:
        - containerPort: 3000
        - name: ssh-git-servers-config
          mountPath: /root/.ssh/config
          subPath: ssh_config
        - name: ssh-git-servers-config
          mountPath: /root/.gitconfig
          subPath: git_config
        - name: ssh-keys
          mountPath: /ssh-keys
```
