### ISSUE TITLE
Bad default config file

### ISSUE THREAD

**Issue by VihanAgarwal97** [gomods/athens#1614]
**Describe the bug**
Bad env variable config in athens.

**Error Message**
```
$ kubectl logs -f athens-athens-proxy-54b4cd5954-44p4v -n pipeline
2020-05-12 21:13:30.096320 I | could not load config file: envconfig.Process: assigning ATHENS_STORAGE_S3_AWS_FORCE_PATH_STYLE to ForcePathStyle: converting '' to type bool. details: strconv.ParseBool: parsing "": invalid syntax
```

**To Reproduce**
Install  athens on helm (v 2.11.0) using the following command - 

```
helm repo add gomods https://athens.blob.core.windows.net/charts
helm repo update
helm upgrade athens --install \
     --namespace pipeline gomods/athens-proxy\
     -f ./Pipeline/Athens/config.yml
```

With the following configs - 
```
replicaCount: 1
image:
  registry: docker.io
  repository: gomods/athens
  tag: v0.8.1
  pullPolicy: IfNotPresent

livenessProbe:
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

service:
  ## Additional annotations to apply to the service
  annotations: {}
  ## Port as exposed by the service
  servicePort: 80
  ## Type of service; valid values are "ClusterIP", "LoadBalancer", and
  ## "NodePort". "ClusterIP" is sufficient in the case when the Proxy will be used
  ## from within the cluster. To expose externally, consider a "NodePort" or "LoadBalancer" service.
  type: ClusterIP

storage:
  type: s3
  s3:
    # you must set s3 bucket and region when running 'helm install'
    region: "us-west-2"
    bucket: "<somename>-athens-proxy"

# Extra annotations to be added to the athens pods
annotations: 
  iam.amazonaws.com/role: "athens-proxy"

jaeger:
  enabled: false

resources: 
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi

```

**Expected behavior**
Expected athens to start up without any errors. To fix this I added this to the `config.yml` file - 
```
configEnvVars:
  - name: ATHENS_STORAGE_S3_AWS_FORCE_PATH_STYLE 
    value: "false"
```
However, now the readiness probe is failing - 
```
Events:
  Type     Reason     Age                  From                                                  Message
  ----     ------     ----                 ----                                                  -------
  Normal   Scheduled  13m                  default-scheduler                                     Successfully assigned pipeline/athens-athens-proxy-f9c6b8c6d-t4wtn to <redacted ip>
  Normal   Pulled     13m                  kubelet, <redacted ip>  Container image "docker.io/gomods/athens:v0.8.1" already present on machine
  Normal   Created    13m                  kubelet,  <redacted ip> Created container athens-athens-proxy
  Normal   Started    13m                  kubelet,  <redacted ip>  Started container athens-athens-proxy
  Warning  Unhealthy  3m1s (x60 over 12m)  kubelet,  <redacted ip>l  Readiness probe failed: HTTP probe failed with statuscode: 500
```
```
INFO[9:40PM]: incoming request	http-method=GET http-path=/healthz http-status=200
INFO[9:40PM]: incoming request	http-method=GET http-path=/readyz http-status=500
```

**Environment (please complete the following information):**
 - OS: linux 64
 - Go version : 1.12
 - Proxy version :
```
NAME                          	REVISION	UPDATED                 	STATUS  	CHART                          	APP VERSION	NAMESPACE
athens                        	1       	Tue May 12 17:14:24 2020	DEPLOYED	athens-proxy-0.4.10            	0.8.1      	pipeline
```
 - Storage (fs/mongodb/s3 etc.) : s3
