### ISSUE TITLE
Fail to access private bitbucket repository get 404

### ISSUE THREAD

**Issue by jdnielsBinus** [gomods/athens#1773]
Hi,

I want to integrate Athens with bitbucket, but always getting Error response 404, I've followed the steps in the documentation

<img width="852" alt="image" src="https://user-images.githubusercontent.com/106030029/169965279-9775a89c-b347-48ec-8348-3a2a0b1cd459.png">

```
docker run --rm -d \
    -v "$PWD/$ATHENS_STORAGE:/var/lib/athens" \
    -v "$PWD/gitconfig/.gitconfig:/root/.gitconfig" \
    -v "${SSH_AUTH_SOCK}:/.ssh_agent_sock" \
    -e "SSH_AUTH_SOCK=/.ssh_agent_sock" \
    -e ATHENS_DISK_STORAGE_ROOT=/var/lib/athens -e ATHENS_STORAGE_TYPE=disk --name athens-proxy -p 3000:3000 gomods/athens
```

**Comment by mattb18** [comment]
https://community.atlassian.com/t5/Bitbucket-questions/Bitbucket-API-always-return-404/qaq-p/1981433

I think this may be related to this issue

**Comment by DrPsychick** [comment]
@jdnielsBinus please let us know if the issue is resolved with the new RC v0.12.0-rc1

**Comment by jdnielss** [comment]
still can't, but I can sometimes download the repository

**Comment by jdnielss** [comment]
```
version: '3.3'
services:
    athens:
        volumes:
            - '$PWD/$ATHENS_STORAGE:/var/lib/athens'
            - '$PWD/.gitconfig:/root/.gitconfig'
            - '$PWD/ssh-keys:/root/.ssh'
        environment:
            - ATHENS_DISK_STORAGE_ROOT=/var/lib/athens
            - ATHENS_STORAGE_TYPE=disk
            - ATHENS_GONOSUM_PATTERNS=bitbucket.org/fundtastic
            - GOSUMDB=off
        container_name: athens-proxy
        ports:
            - '3000:3000'
        image: 'gomods/athens:v0.12.0'
```

this is my docker-compose, and I get error 
```"WARNING: The ATHENS_STORAGE variable is not set. Defaulting to a blank string."```
