### ISSUE TITLE
Unix socket is not removed if athens crashes

### ISSUE THREAD

**Issue by christoffer-eide** [gomods/athens#1908]
**Describe the bug**
We have been testing the unix socket feature implemented in https://github.com/gomods/athens/pull/1865
If athens is killed (for example OOMKilled by k8s), the socket file is not removed. 
When athens is terminated gracefully, the socket file is removed.

**Error Message**
When athens is restarted after a crash, it fails to start:
```
error listening on Unix domain socket /var/run/athens/athens.sock: listen unix 
/var/run/athens/athens.sock: bind: address already in use
```

**To Reproduce**
We run athens in k8s with shared volumes for the socket, but it can be reproduced by using docker:
```
~ $ docker run -v /tmp:/tmp -e "ATHENS_UNIX_SOCKET=/tmp/athens.sock" --rm --name athens-socket-test -d gomods/athens:v0.13.0
6f06704141c14d266e5f5ae77e6d1eda3bd60ce69e3793a855246bac2c2fb6a1
~ $ docker kill athens-socket-test
athens-socket-test
~ $ docker run -v /tmp:/tmp -e "ATHENS_UNIX_SOCKET=/tmp/athens.sock" --rm --name athens-socket-test gomods/athens:v0.13.0
INFO[9:54AM]: Exporter not specified. Traces won't be exported
2023/12/19 09:54:56 Starting application at Unix domain socket /tmp/athens.sock
2023/12/19 09:54:56 error listening on Unix domain socket /tmp/athens.sock: listen unix /tmp/athens.sock: bind: address already in use
~ $ ls /tmp/athens.sock
/tmp/athens.sock
~ $ rm /tmp/athens.sock
~ $ docker run -v /tmp:/tmp -e "ATHENS_UNIX_SOCKET=/tmp/athens.sock" --rm --name athens-socket-test gomods/athens:v0.13.0
INFO[9:55AM]: Exporter not specified. Traces won't be exported
2023/12/19 09:55:54 Starting application at Unix domain socket /tmp/athens.sock
```

**Expected behavior**
During startup, the socket file should be removed if it exists.

**Environment (please complete the following information):**
 - OS:  Linux 64bit
 - Go version : 1.20
 - Proxy version : v0.13.0
 - Storage : S3

**Comment by DrPsychick** [comment]
Would this not better be suited to be solved in the k8s deployment (helm chart or so), because silently overwriting/deleting an existing socket - I don't know if that is the right approach. I would favour "fail early" and expose that the socket is already there, as it is.

**Comment by christoffer-eide** [comment]
It's possible to implement some kind of workaround in k8s, but it's not straight forward.
We ran into this issue when athens was OOMKilled, and was unable to restart as the socket file was left behind. 

I see your point of not silently deleting an existing socket file, my use case is probably a bit k8s specific. 
Would it be an option to make it configurable (`ATHENS_UNIX_SOCKET_DELETE_IF_EXISTS=true|false`)?

**Comment by DrPsychick** [comment]
Would an init container, "preparing the volume" not be sufficient for a k8s deployment? If you're using the official helm chart, I'd rather support custom init containers for that to solve this k8s specific issue.

https://github.com/gomods/athens-charts

**Comment by christoffer-eide** [comment]
If a container crashes, the init container is not executed, so that won't work unfortunately. 
Not sure if it makes sense to support this in the helm charts. Running athens using a socket requires some kind of proxy in front of it to be usable. And the helm charts doesn't support multiple containers in the deployment.

I have found a way to work around this issue by using abstract sockets. These sockets does not use the file system.
We build our custom athens docker image to install some required tooling, including `curl` which makes it easier to implement the live and readiness probes:
```
FROM gomods/athens:v0.13.0
RUN wget -c "https://github.com/Avinode/git-credential-github-apps/releases/download/v1.2.0/git-credential-github-apps_1.2.0_${TARGETOS}_${TARGETARCH}.tar.gz" -O - \
      | tar -xz -C /usr/local/bin/

RUN apk --no-cache add curl
USER athens
```

Then we run a deployment with two containers, where one of them is a reverse proxy.
```
containers:
  - name: proxy
    image: proxy-image
    ports:
      - name: http
        containerPort: 8080
    env:
      - name: PORT
        value: "8080"
      - name: PROXY_URL
        value: "unix://athens/@/var/run/athens/athens.sock"        
  - name: athens
    image: custom-athens-docker-image
    env:
      - name: ATHENS_UNIX_SOCKET
        value: "@/var/run/athens/athens.sock"
    readinessProbe:
      exec:
        command:
          - sh
          - -c
          - curl --fail --abstract-unix-socket $(echo "$ATHENS_UNIX_SOCKET" | cut -d @ -f 2) http://athens/healthz
      initialDelaySeconds: 10
      periodSeconds: 3
      failureThreshold: 3
    livenessProbe:
      exec:
        command:
          - sh
          - -c
          - curl --fail --abstract-unix-socket $(echo "$ATHENS_UNIX_SOCKET" | cut -d @ -f 2) http://athens/healthz
      initialDelaySeconds: 10
      periodSeconds: 3
      failureThreshold: 3
```
Thanks for the feedback @DrPsychick , appreciate it 👍
