### ISSUE TITLE
.netrc not working in container with application

### ISSUE THREAD

**Issue by YannickTeKulve** [gomods/athens#2008]
**Describe the bug**
I'm getting the following error with the the .netrc file

<pre>
0eef3165cdc: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information

</pre>

I'm using the helm chart with .netrc enabled. It's correctly moved to the (root) home dir. When I run the `go mod download github.com/myorg/mymod@v0.0.1` from the root home folder in the container it correctly downloads the file. But when it try it with the proxy it does not work. I have also set the GOPROXY and GONOSUM locally correct (downloading also works without the proxy). 

values.yaml:
```
ingress:
  enabled: true
  className: "nginx"
  tls:
    - hosts:
        - "placeholder"
      secretName: placeholder
    - host: placeholder
      paths:
        - path: /
          pathType: ImplementationSpecific

upstreamProxy:
  enabled: true
  url: "https://proxy.golang.org"

storage:
  type: minio
  minio:
    endpoint: placeholder
    accessKey: placeholder
    secretKey: placeholder
    bucket: "placeholder"
netrc:
  enabled: true
  existingSecret: mysecret
configEnvVars:
  - name: ATHENS_GONOSUM_PATTERNS
    value: "github.com/myorg/*"
  - name: GONOSUMDB
    value: "github.com/myorg/*"
  - name: ATHENS_LOG_LEVEL
    value: TRACE
```

**To Reproduce**
run go mod download

**Expected behavior**
It downloads the module

**Environment (please complete the following information):**
 - OS: k8s
 - Go version : 1.23
 - Proxy version : v0.15.4
 - Storage (fs/mongodb/s3 etc.) :minio
